# Site settings
title: Maria Ziemer
name: Maria Ziemer

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Kyrune
 - title: LinkedIn
   url: https://www.linkedin.com/in/maria-ziemer-780178156/

#Any buzzword skills you want to include
skills:
 - HTML
 - CSS
 - JavaScript (JS)
 - Flexbox
 - Bootstrap
 - jQuery
 - Git & GitHub
 - Node & NPM
 - Angular
 - TypeScript (TS)
 - React
 - Design Principles
 - Agile Methodologies
 - REST
 - SQL & NoSQL
 - Express
 - MongoDB
 - Mongoose

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Web Developer Intern
   start: 2019
   end: Ongoing
   employer: FaithNetwork
   description: FaithNetwork is a remote team of developers who focuses on building websites and simplifying processes, such as charity and live streaming, for churches. The team possesses their own CMS, streamlining the build process via templates and agile communication. <br/> I am being trained to use the team's custom CMS and manage the build stage of websites.

#Education is required
education:
 - level: Professional Certificate
   date: 2018 - 2019
   subject: Full Stack Web Development in JavaScript
   school: Bethel School of Technology
education:
 - level: Bachelor of Arts (B.A.)
   date: 2012 - 2014
   subject: English, with an emphasis on creative writing
   school: Thomas Edison State University

#List of interesting Github repo/projects to include - optional
github:
 - bethel-school-of-technology/mindstorm-frontend
 - bethel-school-of-technology/mindstorm-backend
 - Kyrune/Portfolio-Project
 - Kyrune/Ionic-4-L05

intro: |
  I am a full stack web developer in JavaScript with an interest in front-end development and web design. My goal is to improve customer experience through attention to detail, organizational skills, and critical thinking. I am pursuing opportunities to provide coding skills, teamwork, and creativity to the work environment, with the intent of bringing passion and life to the team.
